### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by ghost** [dkapexhiu/board-game#3]
Downloaded the ZIP folder onto a Mac OS but the game isn't opening.
I'd recommend you a show guide on how to start playing, or you can tell me what to do and then I can push a request.

**Comment by dkapexhiu** [comment]
For running the game it is necessary to start a web server first. I am using XAMPP for windows, but it is also avaiable for Mac OS: https://www.apachefriends.org/download.html
Just install the web server, configure the program and free the ports (or change the ports) to make Apache Server run and then put the files of the game inside htdocs folder in the installation folder of the program. 
For the installation steps you can see this tutorial: http://www.letscodepro.com/install-xampp-on-mac-osx/
If you need a programming environment to run the code, you can install Visual Studio Code: 
https://code.visualstudio.com/download
then to start a webserver to test the game you can see this guide for MacOS:
https://gist.github.com/donmccurdy/20fb112949324c92c5e8
If you need further assistance please let me know.

**Comment by ghost** [comment]
The requirements to run the game seem so complex. It needs to be simplified so other user will find it accessible without coming across simple issues. I think that should be an important thing to sort out. What do you think ?

**Comment by dkapexhiu** [comment]
For starting a server for the development of the game it is a bit complicated! 
But for playing the game, it is needed only to open this web address on your browser: 
https://dkapexhiu.github.io/board-game/
